# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thornode_client
from thornode_client.api.keygen__keysign_api import KeygenKeysignApi  # noqa: E501
from thornode_client.rest import ApiException


class TestKeygenKeysignApi(unittest.TestCase):
    """KeygenKeysignApi unit test stubs"""

    def setUp(self):
        self.api = thornode_client.api.keygen__keysign_api.KeygenKeysignApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_keygen(self):
        """Test case for get_keygen

        Get Keygen  # noqa: E501
        """
        pass

    def test_get_keysign(self):
        """Test case for get_keysign

        Get Keysign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
