# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thornode_client
from thornode_client.models.pool import Pool  # noqa: E501
from thornode_client.rest import ApiException


class TestPool(unittest.TestCase):
    """Pool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPool(self):
        """Test Pool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thornode_client.models.pool.Pool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
