# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thornode_client
from thornode_client.api.nodes_api import NodesApi  # noqa: E501
from thornode_client.rest import ApiException


class TestNodesApi(unittest.TestCase):
    """NodesApi unit test stubs"""

    def setUp(self):
        self.api = thornode_client.api.nodes_api.NodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_a_node(self):
        """Test case for get_a_node

        Get a node  # noqa: E501
        """
        pass

    def test_get_all_nodes(self):
        """Test case for get_all_nodes

        Get all nodes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
