# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import thornode_client
from thornode_client.models.chain_address import ChainAddress  # noqa: E501
from thornode_client.rest import ApiException


class TestChainAddress(unittest.TestCase):
    """ChainAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChainAddress(self):
        """Test ChainAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thornode_client.models.chain_address.ChainAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
