# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thornode_client.configuration import Configuration


class OutboundQueue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'swap': 'float',
        'outbound': 'float',
        'internal': 'float'
    }

    attribute_map = {
        'swap': 'swap',
        'outbound': 'outbound',
        'internal': 'internal'
    }

    def __init__(self, swap=None, outbound=None, internal=None, _configuration=None):  # noqa: E501
        """OutboundQueue - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._swap = None
        self._outbound = None
        self._internal = None
        self.discriminator = None

        if swap is not None:
            self.swap = swap
        if outbound is not None:
            self.outbound = outbound
        if internal is not None:
            self.internal = internal

    @property
    def swap(self):
        """Gets the swap of this OutboundQueue.  # noqa: E501

        number of swaps in the queue  # noqa: E501

        :return: The swap of this OutboundQueue.  # noqa: E501
        :rtype: float
        """
        return self._swap

    @swap.setter
    def swap(self, swap):
        """Sets the swap of this OutboundQueue.

        number of swaps in the queue  # noqa: E501

        :param swap: The swap of this OutboundQueue.  # noqa: E501
        :type: float
        """

        self._swap = swap

    @property
    def outbound(self):
        """Gets the outbound of this OutboundQueue.  # noqa: E501

        number of outbound tx in the queue for customer  # noqa: E501

        :return: The outbound of this OutboundQueue.  # noqa: E501
        :rtype: float
        """
        return self._outbound

    @outbound.setter
    def outbound(self, outbound):
        """Sets the outbound of this OutboundQueue.

        number of outbound tx in the queue for customer  # noqa: E501

        :param outbound: The outbound of this OutboundQueue.  # noqa: E501
        :type: float
        """

        self._outbound = outbound

    @property
    def internal(self):
        """Gets the internal of this OutboundQueue.  # noqa: E501

        number of internal tx in the queue. internal tx include migration,yggdrasil+  # noqa: E501

        :return: The internal of this OutboundQueue.  # noqa: E501
        :rtype: float
        """
        return self._internal

    @internal.setter
    def internal(self, internal):
        """Sets the internal of this OutboundQueue.

        number of internal tx in the queue. internal tx include migration,yggdrasil+  # noqa: E501

        :param internal: The internal of this OutboundQueue.  # noqa: E501
        :type: float
        """

        self._internal = internal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OutboundQueue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OutboundQueue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OutboundQueue):
            return True

        return self.to_dict() != other.to_dict()
