# coding: utf-8

"""
    THORChain API

    This documentation outlines the API for THORChain.  NOTE: This document is a **work in progress**.  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from thornode_client.configuration import Configuration


class TxOutItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chain': 'str',
        'to': 'str',
        'vault_pubkey': 'str',
        'coin': 'Coin',
        'memo': 'str',
        'max_gas': 'Coin',
        'gas_rate': 'str',
        'in_hash': 'str',
        'out_hash': 'str'
    }

    attribute_map = {
        'chain': 'chain',
        'to': 'to',
        'vault_pubkey': 'vault_pubkey',
        'coin': 'coin',
        'memo': 'memo',
        'max_gas': 'max_gas',
        'gas_rate': 'gas_rate',
        'in_hash': 'in_hash',
        'out_hash': 'out_hash'
    }

    def __init__(self, chain=None, to=None, vault_pubkey=None, coin=None, memo=None, max_gas=None, gas_rate=None, in_hash=None, out_hash=None, _configuration=None):  # noqa: E501
        """TxOutItem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._chain = None
        self._to = None
        self._vault_pubkey = None
        self._coin = None
        self._memo = None
        self._max_gas = None
        self._gas_rate = None
        self._in_hash = None
        self._out_hash = None
        self.discriminator = None

        if chain is not None:
            self.chain = chain
        if to is not None:
            self.to = to
        if vault_pubkey is not None:
            self.vault_pubkey = vault_pubkey
        if coin is not None:
            self.coin = coin
        if memo is not None:
            self.memo = memo
        if max_gas is not None:
            self.max_gas = max_gas
        if gas_rate is not None:
            self.gas_rate = gas_rate
        if in_hash is not None:
            self.in_hash = in_hash
        if out_hash is not None:
            self.out_hash = out_hash

    @property
    def chain(self):
        """Gets the chain of this TxOutItem.  # noqa: E501

        chain  # noqa: E501

        :return: The chain of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._chain

    @chain.setter
    def chain(self, chain):
        """Sets the chain of this TxOutItem.

        chain  # noqa: E501

        :param chain: The chain of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._chain = chain

    @property
    def to(self):
        """Gets the to of this TxOutItem.  # noqa: E501

        to address  # noqa: E501

        :return: The to of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this TxOutItem.

        to address  # noqa: E501

        :param to: The to of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def vault_pubkey(self):
        """Gets the vault_pubkey of this TxOutItem.  # noqa: E501

        vault public key  # noqa: E501

        :return: The vault_pubkey of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._vault_pubkey

    @vault_pubkey.setter
    def vault_pubkey(self, vault_pubkey):
        """Sets the vault_pubkey of this TxOutItem.

        vault public key  # noqa: E501

        :param vault_pubkey: The vault_pubkey of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._vault_pubkey = vault_pubkey

    @property
    def coin(self):
        """Gets the coin of this TxOutItem.  # noqa: E501

        coin  # noqa: E501

        :return: The coin of this TxOutItem.  # noqa: E501
        :rtype: Coin
        """
        return self._coin

    @coin.setter
    def coin(self, coin):
        """Sets the coin of this TxOutItem.

        coin  # noqa: E501

        :param coin: The coin of this TxOutItem.  # noqa: E501
        :type: Coin
        """

        self._coin = coin

    @property
    def memo(self):
        """Gets the memo of this TxOutItem.  # noqa: E501

        memo  # noqa: E501

        :return: The memo of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._memo

    @memo.setter
    def memo(self, memo):
        """Sets the memo of this TxOutItem.

        memo  # noqa: E501

        :param memo: The memo of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._memo = memo

    @property
    def max_gas(self):
        """Gets the max_gas of this TxOutItem.  # noqa: E501

        maxmum gas allowed to spend  # noqa: E501

        :return: The max_gas of this TxOutItem.  # noqa: E501
        :rtype: Coin
        """
        return self._max_gas

    @max_gas.setter
    def max_gas(self, max_gas):
        """Sets the max_gas of this TxOutItem.

        maxmum gas allowed to spend  # noqa: E501

        :param max_gas: The max_gas of this TxOutItem.  # noqa: E501
        :type: Coin
        """

        self._max_gas = max_gas

    @property
    def gas_rate(self):
        """Gets the gas_rate of this TxOutItem.  # noqa: E501

        gas rate , signer has to use this gas rate to sign an outbound tx  # noqa: E501

        :return: The gas_rate of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._gas_rate

    @gas_rate.setter
    def gas_rate(self, gas_rate):
        """Sets the gas_rate of this TxOutItem.

        gas rate , signer has to use this gas rate to sign an outbound tx  # noqa: E501

        :param gas_rate: The gas_rate of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._gas_rate = gas_rate

    @property
    def in_hash(self):
        """Gets the in_hash of this TxOutItem.  # noqa: E501

        inbound tx hash  # noqa: E501

        :return: The in_hash of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._in_hash

    @in_hash.setter
    def in_hash(self, in_hash):
        """Sets the in_hash of this TxOutItem.

        inbound tx hash  # noqa: E501

        :param in_hash: The in_hash of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._in_hash = in_hash

    @property
    def out_hash(self):
        """Gets the out_hash of this TxOutItem.  # noqa: E501

        outbound tx hash , this will be available after the txout item had been signed and observed back by bifrost  # noqa: E501

        :return: The out_hash of this TxOutItem.  # noqa: E501
        :rtype: str
        """
        return self._out_hash

    @out_hash.setter
    def out_hash(self, out_hash):
        """Sets the out_hash of this TxOutItem.

        outbound tx hash , this will be available after the txout item had been signed and observed back by bifrost  # noqa: E501

        :param out_hash: The out_hash of this TxOutItem.  # noqa: E501
        :type: str
        """

        self._out_hash = out_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TxOutItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TxOutItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TxOutItem):
            return True

        return self.to_dict() != other.to_dict()
